version: 2

sphinx:
    configuration: docs/conf.py

formats: all

python:
    version: 3.5
    install:
        - method: pip
          path: .
        - method: setuptools
          path: .

conda:
    environment: environment.yml