#!/usr/bin/env python3
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from goodman_pipeline.images import MainApp
import logging

log = logging.getLogger(__name__)

if __name__ == '__main__':
    GOODMAN_CCD = MainApp()
    GOODMAN_CCD()
