#!/usr/bin/env python3
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from goodman_pipeline.core import setup_logging
from goodman_pipeline.images import MainApp

import sys

if '-h' not in sys.argv and \
                '--help' not in sys.argv and \
                '--version' not in sys.argv:
    setup_logging()

if __name__ == '__main__':
    GOODMAN_CCD = MainApp()
    GOODMAN_CCD()
