#!/usr/bin/env python3
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from goodman_pipeline.reduce import Reduce
import logging
import time

log = logging.getLogger(__name__)

if __name__ == '__main__':
    reduce = Reduce()
    while True:
        reduce()
        time.sleep(5)
