#!/usr/bin/env python3
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from pipeline.tools.reference_lamp_factory.create_reference_lamps import \
    ReferenceLibraryFactory

if __name__ == '__main__':
    reference_factory = ReferenceLibraryFactory()
    reference_factory()

